remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: Just a portfolio of my modest knowledge
description: The purpose of this blog is to serve as a collection of materials and as a testament of professional growth. 
